;;; stdlib.el --- the derived standard library (subr/subr-x/seq/cl-lib), ERT-tested  -*- lexical-binding: t; -*-
;; Run me:  elisp examples/stdlib.el
;;
;; These functions are written in elisp in the prelude, on top of the host
;; primitives — the way Emacs bootstraps subr.el. Each is exercised here.
(message "== standard-library demo ==")

(ert-deftest std-predicates ()
  (should (booleanp t))
  (should (booleanp nil))
  (should-not (booleanp 5))
  (should (sequencep (list 1 2)))
  (should (sequencep "x"))
  (should (= (proper-list-p (list 1 2 3)) 3))
  (should-not (proper-list-p 5))
  (should (eq (xor nil 7) 7))
  (should-not (xor 1 1)))

(ert-deftest std-numbers ()
  (should (= (expt 2 10) 1024))
  (should (= (gcd 48 36) 12))
  (should (= (lcm 4 6) 12))
  (should (= (isqrt 50) 7))
  (should (= (cl-signum -3) -1))
  (should (cl-evenp 4))
  (should (cl-oddp 7))
  (should (= (string-to-number "  -42") -42))
  (should (= (string-to-number "abc") 0)))

(ert-deftest std-strings ()
  (should (string= "ab" "ab"))
  (should (string< "abc" "abd"))
  (should (equal (upcase "hello") "HELLO"))
  (should (equal (downcase "HELLO") "hello"))
  (should (equal (capitalize "hello") "Hello"))
  (should (equal (string-reverse "abc") "cba"))
  (should (equal (string-trim "  hi  ") "hi"))
  (should (string-blank-p "   "))
  (should (equal (string-remove-prefix "foo" "foobar") "bar"))
  (should (equal (string-remove-suffix "bar" "foobar") "foo")))

(ert-deftest std-lists ()
  (should (equal (take 3 (list 1 2 3 4 5)) (list 1 2 3)))
  (should (equal (butlast (list 1 2 3)) (list 1 2)))
  (should (equal (flatten-tree (list 1 (list 2 (list 3 4)) 5)) (list 1 2 3 4 5)))
  (should (equal (copy-tree (list 1 (list 2 3))) (list 1 (list 2 3))))
  (should (equal (ensure-list 5) (list 5)))
  (should (equal (ensure-list (list 5)) (list 5)))
  (should (equal (mapcan (lambda (x) (list x x)) (list 1 2)) (list 1 1 2 2)))
  (should (= (assoc-default 'b (list (cons 'a 1) (cons 'b 2))) 2))
  (should (equal (rassoc 2 (list (cons 'a 1) (cons 'b 2))) (cons 'b 2)))
  (should (equal (assq-delete-all 'a (list (cons 'a 1) (cons 'b 2))) (list (cons 'b 2)))))

(ert-deftest std-sort ()
  (should (equal (sort (list 3 1 4 1 5 9 2 6) #'<) (list 1 1 2 3 4 5 6 9)))
  (should (equal (sort (list 3 1 2) #'>) (list 3 2 1)))
  (should (equal (sort (list) #'<) (list))))

(ert-deftest std-seq ()
  (should (equal (seq-take (list 1 2 3 4) 2) (list 1 2)))
  (should (equal (seq-drop (list 1 2 3 4) 2) (list 3 4)))
  (should (equal (seq-subseq (list 1 2 3 4 5) 1 4) (list 2 3 4)))
  (should (equal (seq-uniq (list 1 1 2 3 3 1)) (list 1 2 3)))
  (should (= (seq-min (list 3 1 2)) 1))
  (should (= (seq-max (list 3 1 2)) 3))
  (should (= (seq-position (list 'a 'b 'c) 'b) 1))
  (should (equal (seq-into (list 65 66) 'string) "AB"))
  (should (equal (seq-difference (list 1 2 3 4) (list 2 4)) (list 1 3)))
  (should (equal (seq-intersection (list 1 2 3) (list 2 3 4)) (list 2 3)))
  (should (equal (seq-partition (list 1 2 3 4 5) 2) (list (list 1 2) (list 3 4) (list 5))))
  (should (equal (seq-sort #'< (list 3 1 2)) (list 1 2 3))))

(ert-deftest std-cl ()
  (should (equal (cl-mapcar #'1+ (list 1 2 3)) (list 2 3 4)))
  (should (equal (cl-subseq (list 0 1 2 3 4) 1 3) (list 1 2)))
  (should (= (cl-position 'c (list 'a 'b 'c)) 2))
  (should (= (cl-count 2 (list 1 2 2 3 2)) 3))
  (should (eq (cl-find 'b (list 'a 'b 'c)) 'b))
  (should (equal (cl-remove-duplicates (list 1 1 2 3 3)) (list 1 2 3)))
  (should (= (cl-getf (list :a 1 :b 2) :b) 2)))

(ert-deftest std-macros ()
  (should (= (if-let ((x (assoc 'b (list (list 'b 9))))) (cadr x) 0) 9))
  (should (= (if-let ((x nil)) 1 2) 2))
  (should (equal (when-let ((x (list 1 2))) (cons 0 x)) (list 0 1 2)))
  ;; thread-first: (thread-first 5 (- 1) (* 2)) = (* (- 5 1) 2) = 8
  (should (= (thread-first 5 (- 1) (* 2)) 8))
  ;; thread-last: (thread-last (list 1 2 3 4) (seq-filter #'cl-evenp) (mapcar #'1+)) = (3 5)
  (should (equal (thread-last (list 1 2 3 4) (seq-filter #'cl-evenp) (mapcar #'1+)) (list 3 5))))

(ert-run-tests-batch-and-exit)
